--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: update_live_game_timestamp(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_live_game_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: game_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_events (
    id bigint NOT NULL,
    game_code text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    inning integer NOT NULL,
    inning_half text NOT NULL,
    batting_team text,
    batter_id bigint,
    batter_number text,
    batter_name text,
    event_type text NOT NULL,
    event_description text,
    outs_before integer DEFAULT 0,
    outs_after integer DEFAULT 0,
    runner_first_before boolean DEFAULT false,
    runner_second_before boolean DEFAULT false,
    runner_third_before boolean DEFAULT false,
    runner_first_after boolean DEFAULT false,
    runner_second_after boolean DEFAULT false,
    runner_third_after boolean DEFAULT false,
    runs_scored integer DEFAULT 0,
    rbi integer DEFAULT 0,
    away_score_before integer DEFAULT 0,
    home_score_before integer DEFAULT 0,
    away_score_after integer DEFAULT 0,
    home_score_after integer DEFAULT 0,
    batter_position text,
    balls_before integer DEFAULT 0,
    strikes_before integer DEFAULT 0,
    pitcher_number text,
    pitcher_name text,
    pitch_count_before integer DEFAULT 0,
    pitch_count_after integer DEFAULT 0,
    is_pinch_hitter boolean DEFAULT false,
    replaced_batter_number text,
    replaced_batter_name text
);


--
-- Name: game_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.game_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_rosters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_rosters (
    id bigint NOT NULL,
    game_code text NOT NULL,
    team_side text NOT NULL,
    batting_order integer,
    jersey_number text,
    player_name text,
    "position" text,
    created_at timestamp with time zone DEFAULT now(),
    roster_status text DEFAULT 'active'::text NOT NULL,
    CONSTRAINT game_rosters_roster_status_check CHECK ((roster_status = ANY (ARRAY['active'::text, 'sub'::text, 'used'::text]))),
    CONSTRAINT game_rosters_team_side_check CHECK ((team_side = ANY (ARRAY['home'::text, 'away'::text])))
);


--
-- Name: game_rosters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.game_rosters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_rosters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: live_games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.live_games (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    game_code text NOT NULL,
    home_team text DEFAULT 'HOME'::text NOT NULL,
    away_team text DEFAULT 'AWAY'::text NOT NULL,
    home_score integer DEFAULT 0 NOT NULL,
    away_score integer DEFAULT 0 NOT NULL,
    inning integer DEFAULT 1 NOT NULL,
    inning_half text DEFAULT 'top'::text NOT NULL,
    balls integer DEFAULT 0 NOT NULL,
    strikes integer DEFAULT 0 NOT NULL,
    outs integer DEFAULT 0 NOT NULL,
    runner_first boolean DEFAULT false NOT NULL,
    runner_second boolean DEFAULT false NOT NULL,
    runner_third boolean DEFAULT false NOT NULL,
    status text DEFAULT 'live'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    home_pitcher_number text DEFAULT ''::text,
    home_pitcher_name text DEFAULT ''::text,
    home_pitch_count integer DEFAULT 0 NOT NULL,
    away_pitcher_number text DEFAULT ''::text,
    away_pitcher_name text DEFAULT ''::text,
    away_pitch_count integer DEFAULT 0 NOT NULL,
    current_batter_number text DEFAULT ''::text,
    current_batter_name text DEFAULT ''::text,
    CONSTRAINT live_games_balls_check CHECK (((balls >= 0) AND (balls <= 3))),
    CONSTRAINT live_games_inning_half_check CHECK ((inning_half = ANY (ARRAY['top'::text, 'bottom'::text]))),
    CONSTRAINT live_games_outs_check CHECK (((outs >= 0) AND (outs <= 2))),
    CONSTRAINT live_games_status_check CHECK ((status = ANY (ARRAY['setup'::text, 'live'::text, 'final'::text]))),
    CONSTRAINT live_games_strikes_check CHECK (((strikes >= 0) AND (strikes <= 2)))
);

ALTER TABLE ONLY public.live_games REPLICA IDENTITY FULL;


--
-- Name: game_events game_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_events
    ADD CONSTRAINT game_events_pkey PRIMARY KEY (id);


--
-- Name: game_rosters game_rosters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_rosters
    ADD CONSTRAINT game_rosters_pkey PRIMARY KEY (id);


--
-- Name: live_games live_games_game_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.live_games
    ADD CONSTRAINT live_games_game_code_key UNIQUE (game_code);


--
-- Name: live_games live_games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.live_games
    ADD CONSTRAINT live_games_pkey PRIMARY KEY (id);


--
-- Name: game_rosters_game_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX game_rosters_game_code_idx ON public.game_rosters USING btree (game_code);


--
-- Name: game_rosters_team_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX game_rosters_team_idx ON public.game_rosters USING btree (game_code, team_side);


--
-- Name: live_games live_games_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER live_games_updated_at BEFORE UPDATE ON public.live_games FOR EACH ROW EXECUTE FUNCTION public.update_live_game_timestamp();


--
-- Name: game_events Public game events delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game events delete" ON public.game_events FOR DELETE TO anon USING (true);


--
-- Name: game_events Public game events insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game events insert" ON public.game_events FOR INSERT TO anon WITH CHECK (true);


--
-- Name: game_events Public game events select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game events select" ON public.game_events FOR SELECT TO anon USING (true);


--
-- Name: game_rosters Public game rosters delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game rosters delete" ON public.game_rosters FOR DELETE TO anon USING (true);


--
-- Name: game_rosters Public game rosters insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game rosters insert" ON public.game_rosters FOR INSERT TO anon WITH CHECK (true);


--
-- Name: game_rosters Public game rosters select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game rosters select" ON public.game_rosters FOR SELECT TO anon USING (true);


--
-- Name: game_rosters Public game rosters update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public game rosters update" ON public.game_rosters FOR UPDATE TO anon USING (true) WITH CHECK (true);


--
-- Name: game_rosters Public roster delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public roster delete" ON public.game_rosters FOR DELETE USING (true);


--
-- Name: game_rosters Public roster insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public roster insert" ON public.game_rosters FOR INSERT WITH CHECK (true);


--
-- Name: game_rosters Public roster read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public roster read" ON public.game_rosters FOR SELECT USING (true);


--
-- Name: game_rosters Public roster update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Public roster update" ON public.game_rosters FOR UPDATE USING (true) WITH CHECK (true);


--
-- Name: game_events; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.game_events ENABLE ROW LEVEL SECURITY;

--
-- Name: game_rosters; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.game_rosters ENABLE ROW LEVEL SECURITY;

--
-- Name: live_games; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.live_games ENABLE ROW LEVEL SECURITY;

--
-- Name: live_games public can create live games; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public can create live games" ON public.live_games FOR INSERT TO anon WITH CHECK (true);


--
-- Name: live_games public can read live games; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public can read live games" ON public.live_games FOR SELECT TO anon USING (true);


--
-- Name: live_games public can update live games; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public can update live games" ON public.live_games FOR UPDATE TO anon USING (true) WITH CHECK (true);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE game_events; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.game_events TO anon;
GRANT ALL ON TABLE public.game_events TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.game_events TO service_role;


--
-- Name: SEQUENCE game_events_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.game_events_id_seq TO anon;
GRANT SELECT,USAGE ON SEQUENCE public.game_events_id_seq TO authenticated;


--
-- Name: TABLE game_rosters; Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON TABLE public.game_rosters TO anon;
GRANT ALL ON TABLE public.game_rosters TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.game_rosters TO service_role;


--
-- Name: SEQUENCE game_rosters_id_seq; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,USAGE ON SEQUENCE public.game_rosters_id_seq TO anon;
GRANT SELECT,USAGE ON SEQUENCE public.game_rosters_id_seq TO authenticated;


--
-- Name: TABLE live_games; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE public.live_games TO anon;
GRANT SELECT,INSERT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN,UPDATE ON TABLE public.live_games TO authenticated;
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE public.live_games TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--



--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--



--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--



--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: -
--



--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--



--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--



--
-- PostgreSQL database dump complete
--
